name: lint
on: pull_request

jobs:
  lint:
    name: check_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main
        uses: actions/checkout@main

      - name: Check if all files have lint logs
        run: |
            chmod +x ./checks/lint_files.sh
            ./checks/lint_files.sh